# Generated by Django 5.1.5 on 2025-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "CORE_ORDER_ITEMS",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"managed": False},
        ),
    ]
