# Generated by Django 5.1.5 on 2025-02-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_orderitems_alter_orderitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"managed": False},
        ),
    ]
