# Generated by Django 5.1.5 on 2025-02-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_coupon_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="coupon",
            table="CORE_COUPON",
        ),
    ]
