# Generated by Django 5.1.5 on 2025-02-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_postgres_tables"),
        ("core", "0004_alter_coupon_table"),
    ]

    operations = []
